apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-p1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-p1
  template:
    metadata:
      labels:
        app: producer-p1
    spec:
      containers:
      - name: producer-p1
        image: github.com/weak-head/spark-streaming/producer:0.0.1
        env:
        - name: kafkaHost
          value: "kafka.kafka.svc.cluster.local:9092"
        - name: kafkaTopic
          value: "zeus"
        - name: producerPrefix
          value: "p1"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"